### ISSUE TITLE
Taxonomy/functional profile for all the samples

### ISSUE THREAD

**Issue by ghost** [avishekdutta14/iMAGine#3]
Q: Since the assemblies are performed separately, How can I make the functional and taxonomy profile for the samples ? any suggestions? If I want to do the taxonomic and functional profile for the contigs. How can I combine the results or how to d the downstream analysis when the samples are separates.

**Comment by avishekdutta14** [comment]
Hi,

You can look at the taxonomy and functional profile at two levels from the data generated by iMAGine.

1. For whole metagenome data (contigs generated by iMAGine) - You can find the details and tools for taxonomic and functional annotations [here](https://github.com/avishekdutta14/iMAGine#for-annotating-assembled-contigs-whole-metagenome).
2. For MAGs, You can find the details and tools for taxonomic and functional annotations [here](https://github.com/avishekdutta14/iMAGine#for-annotating-magsgenomes). 

You can run most tools in a loop for all the samples. You can also run them separately.

You can use the output from the tools you used (for assessing taxonomic and functional profiles) and then use R or Python to compare them. At present, the iMAGine repository does not have any scripts for comparisons. But we will develop the repository for including such tools in the future. I hope this helps.

Best,
Avishek
