### ISSUE TITLE
mimalloc: error: unable to allocate OS memory (63749226496 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only$

### ISSUE THREAD

**Issue by ghost** [avishekdutta14/iMAGine#4]
Hello, 
I have been trying to run iMAGine for a few times. The analysis stops at meta spade in some samples and some other it stops at check. First I gussed it is because I am running the pipeline in a script in parallel. So I run on only one sample to see if the analysis will be completed. But with this sample it stoped at meta spade and did not produce QUAST and the following output. The spades log give this error:
mimalloc: error: unable to allocate OS memory (63749226496 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only$
mimalloc: process info:
I found that it maybe due to some memory limit and mostly happens with large dataset. Is it possible to split my large sample faster to be able to process them using spade? Or what do you recommend ? 
Thanks!

**Comment by avishekdutta14** [comment]
If your computer has more than 300 GB of memory, I suggest editing the iMAGine code in Line number 34. Change the value of the memory flag (-m) to a higher number. Currently, it is 300, which means that metaSPAdes will terminate if the process requires more than 300 GB of memory. For e.g., if you have 500 GB of RAM available on your system, I suggest increasing the number to 450 (suggest using 90% of available memory) from 300. If the issue still persists, downsampling might be a solution.
