### ISSUE TITLE
bbnorm normalize read covarege 

### ISSUE THREAD

**Issue by ghost** [avishekdutta14/iMAGine#6]
Hello, 
I want to use iMAGine to analyse different samples with uneven sequencing depths and I want to normalize the reads using bbnorm or any other tool. How can I go about this?

**Comment by avishekdutta14** [comment]
Hi,
You have to first subsample/normalize the reads to the desired sequencing depth and then run them on iMAGine. You can conduct subsampling using reformat.sh (Details can be found [here](https://github.com/BioInfoTools/BBMap/blob/master/sh/reformat.sh)) or you can normalize using bbnorm.sh (Details can be found [here](https://github.com/BioInfoTools/BBMap/blob/master/sh/bbnorm.sh)). I think neither of the tools will lose the pairing information or quality information that is required for iMAGine input.
