### ISSUE TITLE
 mean coverage_relative abundance

### ISSUE THREAD

**Issue by ghost** [avishekdutta14/iMAGine#7]
I have run iMAGine on the samples; I recovered the MAGs. I want to calculate the relative abundance of my bins in each sample. What do you think is the right way to do it? Here is what I did: For each sample, I used the output "refined_stats.csv" in the binning folder,  summed the coverages, and divided each bin's mean coverage by the overall mean coverage in each sample. I am still determining how the mean coverage is calculated or parsed from the pipeline and whether it needs to be scaled as I did. I would appreciate any guidance you can give me.

**Comment by avishekdutta14** [comment]
If you want to calculate the abundance of the MAGs, you can use the [mag_abund.py](https://github.com/avishekdutta14/iMAGine/tree/main/Utilities) script present in the Utilities folder of iMAGine.

**Comment by ghost** [comment]
Thank you for the insight! I used it and it worked and produced the mapped_reads_per_bin where I can find the abundance of each bin in the metagenome. "The relative abundance of each MAG was calculated as the total number of reads mapped to a MAG divided by the total number of reads in the corresponding metagenome sample". My question here is "the total number of reads." Do we consider the raw reads, the filtered ones? or the contigs? 

This script is based on the methods reported in [Hervé et al., 2020](https://peerj.com/articles/8614/) and [Hua et al., 2019](https://www.nature.com/articles/s41467-019-12574-y).

**Comment by avishekdutta14** [comment]
Generally, we should use the number of filtered reads.

**Comment by ghost** [comment]
Thank you so much. I really appreciate all your insights.  I wish you keep the posts as I know some may have similar questions and they may benefit from such information.

**Comment by avishekdutta14** [comment]
I close the posts that are addressed. This helps me track and manage the posts. You can find all the closed posts (Older closed Issues) under the "Closed" Tab in Issues.
